const{chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{for(const [width,height]of[[320,568],[375,812]]){const p=await b.newPage({viewport:{width,height},hasTouch:true});await p.goto(pathToFileURL(path.resolve('index.html')).href+'?check=1&scenario=room');await p.evaluate(()=>{gameState.inventory.groom_comb=8;gameState.ui.modal=null;render(gameState);});
 const cdp=await p.context().newCDPSession(p);async function hold(selector){const r=await p.locator(selector).boundingBox(),point={x:r.x+r.width/2,y:r.y+r.height/2};await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[point]});await p.waitForTimeout(750);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 assert(await p.locator('[data-action="touch-now"]').evaluate(n=>!n.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))));
 await hold('[data-action="touch-now"]');await p.locator('[data-contact="comb"]').click();assert.equal(await p.evaluate(()=>gameState.ui.touchMode),'comb');await hold('[data-action="call-cat"]');assert(await p.locator('#cat-nickname').isVisible());await p.locator('[data-action="close-modal"]').first().click();
 await p.goto(pathToFileURL(path.resolve('index.html')).href+'?check=1&scenario=room');
 await p.evaluate(()=>{const cat=getCat(gameState);cat.body.hair=[{id:'test-hair',x:45,y:65}];gameState.ui.equippedCleaner='starter_clean';gameState.ui.careAnimation=null;render(gameState);});
 const hair=await p.locator('[data-hair="test-hair"]').boundingBox();
 const tool=await p.locator('[data-command="clean"]').boundingBox();await p.mouse.move(tool.x+tool.width/2,tool.y+tool.height/2);await p.mouse.down();await p.mouse.move(hair.x+hair.width/2-12,hair.y+hair.height/2,{steps:12});await p.mouse.move(hair.x+hair.width/2+12,hair.y+hair.height/2,{steps:4});await p.mouse.up();
 assert.equal(await p.evaluate(()=>getCat(gameState).body.hair.length),0);await p.screenshot({path:`tests/screenshots/hold-roller-${width}.png`});await p.close();}console.log('PASS touch long-press menus, comb selection, context menu prevention and light roller stroke');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
