const {chromium}=require('playwright');const assert=require('node:assert/strict'),path=require('node:path');const {pathToFileURL}=require('node:url');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:375,height:812},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 await p.evaluate(()=>{titleScreenOpen=false;gameState.campaign.phase='room';gameState.onboarding.status='done';const cat=getCat(gameState);cat.status='raising';cat.name='はる';cat.types=['human','touch'];cat.heart=95;cat.heartCap=100;gameState.ui.guideExpanded=false;gameState.inventory.groom_comb=3;gameState.inventory.groom_wipe=2;render(gameState);});
 const touch=p.locator('[data-action="touch-now"]');
 for(const width of [320,375,430]){await p.setViewportSize({width,height:812});const main=await p.locator('.main-command-row').boundingBox(),sub=await p.locator('.sub-command-row').boundingBox();assert(main.x>=0&&sub.x>=main.x+main.width&&sub.x+sub.width<=width);const call=await p.locator('[data-action="call-cat"]').boundingBox(),t=await touch.boundingBox();assert(t.y>call.y+call.height);assert(await p.locator('.sub-command strong').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth)));}
 await p.setViewportSize({width:375,height:812});await p.screenshot({path:'tests/screenshots/v019-controls.png'});
 const toy=await p.evaluate(()=>gameState.ui.equippedHand);
 await touch.tap();assert.equal(await p.evaluate(()=>gameState.ui.modal),null);assert.equal(await p.evaluate(()=>gameState.ui.careAnimation?.mode),'pet');assert.equal(await p.locator('.cat-object.walking,.cat-object.jumping').count(),0);await p.screenshot({path:'tests/screenshots/v019-pet.png'});await p.waitForTimeout(1250);assert(await p.evaluate(()=>gameState.ui.usedHandItems.action_pet));assert.equal(await p.evaluate(()=>gameState.ui.equippedHand),toy);
 // Long press selects a mode; neither long press nor selecting an entry consumes a use.
 const r=await touch.boundingBox();await p.mouse.move(r.x+20,r.y+20);await p.mouse.down();await p.waitForTimeout(700);await p.mouse.up();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>gameState.ui.modal),'touchTools');assert.equal(await p.evaluate(()=>gameState.ui.careAnimation),null);
 await p.locator('[data-contact="comb"]').tap();assert.equal(await p.evaluate(()=>gameState.inventory.groom_comb),3);await touch.tap();assert.equal(await p.evaluate(()=>gameState.ui.careAnimation?.mode),'comb');await p.waitForTimeout(1250);assert.equal(await p.evaluate(()=>gameState.inventory.groom_comb),2);assert(await p.evaluate(()=>getCat(gameState).body.groomedTicks>0));
 await p.evaluate(()=>dispatch({type:'CONTACT_ACTION',contact:'wipe'}));await touch.tap();await p.waitForTimeout(1250);assert.equal(await p.evaluate(()=>gameState.inventory.groom_wipe),1);
 await p.evaluate(()=>dispatch({type:'CONTACT_ACTION',contact:'pickup'}));await touch.tap();await p.waitForTimeout(1250);assert(await p.evaluate(()=>gameState.ui.holdingCat));assert((await touch.innerText()).includes('おろす'));await touch.tap();assert.equal(await p.evaluate(()=>gameState.ui.holdingCat),false);
 // Low-heart pickup still refuses; button execution doesn't bypass affinity/stage rules.
 await p.evaluate(()=>{gameState.cats[0].heart=50;render(gameState);});await touch.tap();await p.waitForTimeout(1200);assert.equal(await p.evaluate(()=>gameState.ui.pickupResult),'fled');
 // Out of stock opens the chooser without a phantom animation/use.
 await p.evaluate(()=>{gameState.inventory.groom_comb=0;dispatch({type:'CONTACT_ACTION',contact:'comb'});});await touch.tap();assert.equal(await p.evaluate(()=>gameState.ui.modal),'touchTools');assert.equal(await p.evaluate(()=>gameState.ui.careAnimation),null);await p.locator('.sheet-close').tap();
 // Movement cancels a long press, and lifting the finger must not execute touch.
 await p.evaluate(()=>dispatch({type:'CONTACT_ACTION',contact:'pet'}));const c=await touch.boundingBox();await p.mouse.move(c.x+20,c.y+20);await p.mouse.down();await p.mouse.move(c.x-30,c.y-35,{steps:6});await p.waitForTimeout(700);await p.mouse.up();assert.equal(await p.evaluate(()=>gameState.ui.careAnimation),null);assert.equal(await p.evaluate(()=>gameState.ui.modal),null);
 await touch.focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>gameState.ui.careAnimation?.mode),'pet');await p.waitForTimeout(1200);
 // Freeze at the displayed location while touching; no jump to a roam destination.
 const frozen=await p.evaluate(()=>{const a=getAvailableRoamPoints(gameState)[0],z=getAvailableRoamPoints(gameState)[1];gameState.ui.roamIndex=z.index;render(gameState);const anim=animateCatWalk(a,z);anim.pause();anim.currentTime=900;const visible=getVisibleTouchPoint();dispatch({type:'TOUCH_NOW',point:visible});const after=getCatPoint(gameState);return Math.abs(after.x-visible.x)<.001&&Math.abs(after.y-visible.y)<.001;});assert(frozen);
 await p.waitForTimeout(1250);assert.deepEqual(errors,[]);console.log('PASS v019: right-side vertical controls, tap pet/comb/wipe/pickup/release, affinity refusal, no stock, long press, cancelled drag, keyboard, motion anchor, toy retained');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
