const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');const {pathToFileURL}=require('node:url');
async function drag(p,a,b){const x=await p.locator(a).boundingBox(),y=await p.locator(b).boundingBox();await p.mouse.move(x.x+x.width/2,x.y+x.height/2);await p.mouse.down();await p.mouse.move(y.x+y.width/2,y.y+y.height*.7,{steps:14});await p.mouse.up();}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const p=await browser.newPage({viewport:{width:375,height:812}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('index.html')).href);
 await p.locator('[data-action="start-game"]').click();for(let i=0;i<3;i++)await p.locator('[data-action="next-story"]').click();await p.locator('[data-action="toggle-guide"]').click();
 await drag(p,'[data-field-drag="trap"]','.field-scene');await drag(p,'[data-field-drag="bait"]','.trap');await p.locator('[data-action="finish-field-prep"]').click();await p.locator('[data-action="open-trap"]').waitFor({timeout:6000});await p.locator('[data-action="open-trap"]').click({force:true});await p.locator('[data-action="go-clinic"]').waitFor({timeout:9000}).catch(async e=>{await p.screenshot({path:'tests/screenshots/v020-flow-failure.png'});console.log(errors,await p.evaluate(()=>({phase:gameState.campaign,html:document.querySelector('.campaign-actions')?.innerHTML})));throw e;});await p.locator('[data-action="go-clinic"]').click();await p.locator('[data-action="start-naming"]').waitFor();await p.locator('[data-action="start-naming"]').click();await p.locator('#campaign-cat-name').fill('こはる');await p.screenshot({path:'tests/screenshots/v020-naming.png'});await p.locator('[data-action="start-intake"]').click();
 assert.equal(await p.evaluate(()=>gameState.coins),38);
 // Only buy positively matched furniture, using the real reducer and remaining funds.
 await p.evaluate(()=>{const options=SHOP_CATALOG.filter(p=>p.category==='furniture').map(p=>({...p,score:getAffinity(getCat(gameState),getItem(p.id)).score})).filter(p=>p.score>0).sort((a,b)=>a.price-b.price);for(const p of options){if(getRoomComfortBreakdown(gameState).canExit)break;if(!owned(gameState,p.id))dispatch({type:'BUY_SHOP_ITEM',itemId:p.id});if(owned(gameState,p.id)&&!getPlaced(getRoom(gameState)).some(x=>x.itemId===p.id))dispatch({type:'TOGGLE_PLACED_ITEM',itemId:p.id});}});
 assert.equal(await p.evaluate(()=>getRoomComfortBreakdown(gameState).canExit),true);await p.locator('[data-action="call-intake-cat"]').click();await p.locator('[data-action="close-schedule-intro"]').waitFor();await p.locator('[data-action="close-schedule-intro"]').click();assert.equal(await p.evaluate(()=>gameState.campaign.phase),'room');await p.screenshot({path:'tests/screenshots/v020-first-room.png'});
 const outcomes=await p.evaluate(()=>[95,20].map(heart=>{const s=structuredClone(gameState);s.cats[0].heart=heart;s.cats[0].body.days=7;s.cats[0].body.weight=3500;s.cats[0].body.sick=false;s.cats[0].body.hunger=false;s.campaign.phase='graduation';s.coins=50;const n=reduceGameState(s,{type:'SEND_EVENT'});return n.campaign.outcome;}));assert.deepEqual(outcomes,['adopted','tnr']);assert.deepEqual(errors,[]);console.log('PASS v020: actual title → rescue drag → capture → clinic → name → purchased furniture → intake → room; adoption/TNR reducers');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
