const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('index.html')).href);
 await p.evaluate(()=>{titleScreenOpen=false;gameState.onboarding.status='done';gameState.campaign.phase='room';gameState.cats[0].status='raising';gameState.ui.modal=null;gameState.cats[0].body.vomit=2;gameState.cats[0].body.litter=2;gameState.cats[0].body.foodLevel=80;gameState.cats[0].body.hair=Array.from({length:8},(_,i)=>({id:'art'+i,x:16+i*7,y:65+i%3*7}));render(gameState);});
 assert.equal(await p.locator('.paper-menu-icon').count(),5);assert.equal(await p.locator('.life-hair').count(),8);assert.equal(await p.locator('.life-vomit').count(),1);assert.equal(await p.locator('.life-poop').count(),1);
 assert.equal(await p.locator('.item-bowl .book-furniture-art').evaluate(n=>decodeURIComponent(n.src).includes('viewBox="0 0 100 80"')),true);
 await p.screenshot({path:'tests/screenshots/v023-room.png'});
 await p.evaluate(()=>dispatch({type:'OPEN_SLOT_MENU',tab:'play'}));await p.waitForTimeout(400);await p.screenshot({path:'tests/screenshots/v023-bag.png'});
 for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await p.evaluate(()=>{document.body.innerHTML='<div id="pose-proof" style="display:grid;grid-template-columns:repeat(2,1fr);background:#eee5ce;width:760px"></div>';for(const age of ['adult','kitten'])for(const pose of ['walk','dash','jump']){const box=document.createElement('div');box.innerHTML=`<p>${age} / ${pose}</p><svg viewBox="170 130 380 300" width="350" height="250"></svg>`;document.querySelector('#pose-proof').append(box);const dna={...CatSVG.defaults,age,body:'slim',headCoat:'cream',bodyCoat:'cream',legCoat:'cream',tailCoat:'cream'};const rig=CatSVG.buildCat(box.querySelector('svg'),age+pose,dna,375,1);CatSVG.applyPose(rig,CatSVG.poseModel(pose,.45),.45,pose);if(/NaN|undefined/.test(rig.svg.innerHTML))throw Error('invalid pose');}});await p.setViewportSize({width:800,height:960});await p.screenshot({path:'tests/screenshots/v023-poses.png'});
 assert.deepEqual(errors,[]);console.log('PASS v023: shared SVG life art, 5 menu icons, responsive inventory, adult/kitten poses');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
