const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('index.html')).href);
await p.evaluate(()=>{titleScreenOpen=false;gameState.onboarding.status='done';gameState.campaign.phase='room';gameState.cats[0].status='raising';gameState.ui.modal=null;gameState.ui.careAnimation=null;gameState.ui.equippedCleaner='starter_clean';gameState.cats[0].body.hair=[{id:'rag-test',x:40,y:70}];render(gameState);});
const result=await p.evaluate(()=>{let s=structuredClone(gameState),counts=[];for(let i=0;i<5;i++){s=reduceGameState(s,{type:'RUB_CLEAN',cleanerId:'starter_clean',targets:[{problem:'hair',hairId:'rag-test'}]});counts.push(s.cats[0].body.hair.length);}commandDraft={command:'clean'};const blocked=reduceGameState(s,{type:'TAP_CAT'});commandDraft=null;return {counts,blocked:blocked===s};});assert.deepEqual(result.counts,[1,1,1,1,0]);assert.equal(result.blocked,true);
let b=await p.locator('.main-command[data-command="clean"]').boundingBox(),cat=await p.locator('.cat-object').boundingBox();await p.mouse.move(b.x+b.width/2,b.y+b.height/2);await p.mouse.down();await p.mouse.move(cat.x+cat.width/2,cat.y+cat.height/2,{steps:8});await p.waitForTimeout(750);assert.equal(await p.evaluate(()=>!!gameState.ui.careAnimation||!!gameState.ui.holdingCat),false);assert.equal(await p.locator('.drop-ready').first().evaluate(n=>getComputedStyle(n).outlineStyle),'none');await p.screenshot({path:'tests/screenshots/v024-clean.png'});await p.mouse.up();assert.equal(await p.evaluate(()=>!!gameState.ui.careAnimation||!!gameState.ui.holdingCat),false);
await p.screenshot({path:'tests/screenshots/v024-room.png'});await p.evaluate(()=>dispatch({type:'OPEN_SLOT_MENU',tab:'clean'}));await p.waitForTimeout(350);await p.screenshot({path:'tests/screenshots/v024-bag.png'});
assert.deepEqual(errors,[]);console.log('PASS v024: rag requires 5 passes, cleaning cannot touch cat, no pink target outline, illustrated controls');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
