const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:320,height:520}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const url=pathToFileURL(path.resolve('index.html')).href;
await p.goto(url+'?check=1&scenario=town');assert(await p.locator('[data-area="a2"]').isDisabled());await p.evaluate(()=>dispatch({type:'CHOOSE_AREA',area:'a2'}));assert.equal(await p.evaluate(()=>gameState.ui.modal),null);
await p.goto(url+'?check=1&scenario=tnr-result');assert(await p.locator('.area-unlock-note').isVisible());await p.locator('[data-action="prepare-next"]').click();await p.locator('[data-action="next-rescue"]').click();assert(await p.locator('[data-area="a2"]').isEnabled());await p.locator('[data-area="a2"]').click();await p.locator('[data-action="enter-park"]').waitFor();await p.screenshot({path:'tests/screenshots/v033-park-brief.png'});const r=await p.locator('.area-brief [data-action="close-modal"]').boundingBox();assert(r.y+r.height<=520);
await p.locator('[data-action="enter-park"]').click();assert.equal(await p.evaluate(()=>gameState.campaign.area),'a2');assert(await p.locator('.place-chip').innerText().then(t=>t.includes('公園')));
await p.evaluate(()=>{Object.assign(gameState.campaign,{trapPlaced:true,trapReady:true,trapWaiting:true,bait:['food_dry']});dispatch({type:'OPEN_TRAP'});});assert.equal(await p.evaluate(()=>gameState.campaign.phase),'trapInspect');assert.equal(await p.evaluate(()=>getCat(gameState).age),'kitten');assert.equal(await p.evaluate(()=>getCat(gameState).body.weight),680);assert.equal(await p.evaluate(()=>getCat(gameState).phenotype.age),'kitten');assert.equal(await p.evaluate(()=>getCat(gameState).rescueArea),'a2');
await p.evaluate(()=>{dispatch({type:'GO_CLINIC'});dispatch({type:'START_NAMING'});dispatch({type:'START_INTAKE',name:'こえだ'});});assert.equal(await p.evaluate(()=>getCat(gameState).heart),50);assert.equal(await p.evaluate(()=>getCat(gameState).body.weight),680);
await p.reload();await p.locator('[data-action="start-game"]').click();assert.equal(await p.evaluate(()=>getCat(gameState).rescueArea),'a2');
// Six days of adequate food/water can reach the existing kitten goal without special paid growth multipliers.
const sim=await p.evaluate(()=>{let s=structuredClone(gameState);s.cats[0].status='raising';s.campaign.phase='room';for(let i=0;i<48;i++){Object.assign(s.cats[0].body,{foodLevel:100,waterLevel:100,litter:0,vomit:0});s=advanceRealTicks(s,1);}return {weight:s.cats[0].body.weight,days:s.cats[0].body.days,goal:surgeryEligibility(s).goal};});assert(sim.weight>=sim.goal,JSON.stringify(sim));
// TNR counts and appearances belong to the rescue area, not the first area.
await p.evaluate(()=>{const c=getCat(gameState);Object.assign(c,{status:'raising',heart:20,surgery:{status:'done',completedDay:6},eventVisitDay:7});Object.assign(c.body,{days:6,weight:710,sick:false});Object.assign(gameState.campaign,{phase:'graduation',requiredVisit:null});gameState.coins=50;dispatch({type:'SEND_EVENT'});});assert.equal(await p.evaluate(()=>gameState.album.at(-1).area),'a2');assert.equal(await p.evaluate(()=>gameState.areas.a2.tnrCount),1);assert.equal(await p.evaluate(()=>gameState.areas.a1.tnrCount),1);
await p.evaluate(()=>dispatch({type:'NEXT_RESCUE'}));await p.locator('[data-area="a2"]').click();await p.locator('[data-action="enter-park"]').click();assert.equal(await p.locator('.field-tnr-cat').count(),1);
await p.evaluate(()=>dispatch({type:'BACK_TO_TOWN'}));await p.locator('[data-area="a1"]').click();assert.equal(await p.evaluate(()=>gameState.campaign.area),'a1');
assert.deepEqual(errors,[]);console.log('PASS v033: locked first game, TNR unlock, park kitten capture/intake/reload, attainable growth, area-specific records/TNR, return to first area');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
